# Site settings
title: CPH Intern Landing Page
description: Getting started at CP Handheld Technologies
baseurl: "/CPH_Page" # the subpath of your site, e.g. /blog
url: "https://CPHT.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: CPH Intern Landing Page
user_description: Making dreams a reality
user_title: Making dreams a reality
email: 
twitter_username: 
github_username:  
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

# exclude: ['package.json', 'src' , 'node_modules']
